//Generated by DCG Generator on 2017/12/22/ 10:02
#pragma once
class DCGTestClass
{
public:
    bool mBoolValue;
    int mIntValue;
    DCGTestClass();
    ~DCGTestClass();
    void initTestClass();
    bool getBoolValue();
    void setBoolValue(bool aValue);
    void functionMultipleParams(bool aValue, int aValue);
};
