//Generated by DCG Generator on 2017/12/22/ 10:02

#include "../include/DCGTestClass.h"
DCGTestClass::DCGTestClass()
{

}
DCGTestClass::~DCGTestClass()
{

}
void DCGTestClass::initTestClass()
{

}
bool DCGTestClass::getBoolValue()
{

}
void DCGTestClass::setBoolValue(bool aValue)
{

}
void DCGTestClass::functionMultipleParams(bool aValue, int aValue)
{

}
